# Generated by Django 3.1.6 on 2021-02-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20210206_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meme',
            old_name='name',
            new_name='owner',
        ),
    ]
