# Generated by Django 3.1.6 on 2021-02-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20210206_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meme',
            old_name='owner',
            new_name='name',
        ),
    ]
